### ISSUE TITLE
NoMethodError (undefined method `values' for nil:NilClass)

### ISSUE THREAD

**Issue by juanpastas** [chrismccord/sync#192]
Here is [the trace](https://gist.github.com/juanpastas/61797a79b13836f56452).

I tried this:

```shell
[1] pry(main)> Teacher.sync_scope_definitions
=> nil
[2] pry(main)> Teacher.last.sync_scope_definitions
  Teacher Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('Teacher')  ORDER BY "users"."id" DESC LIMIT 1
NoMethodError: private method `sync_scope_definitions' called for #<Teacher:0x000000028ab3d8>
from /home/pills/.rvm/gems/ruby-2.2.2/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:430:in `method_missing'
[3] pry(main)> Teacher.last.send :sync_scope_definitions
  Teacher Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('Teacher')  ORDER BY "users"."id" DESC LIMIT 1
NoMethodError: undefined method `values' for nil:NilClass
from /home/pills/.rvm/gems/ruby-2.2.2/gems/sync-0.3.5/lib/sync/model_actions.rb:52:in `sync_scope_definitions'
```

**Comment by juanpastas** [comment]
Turned out that I am using STI and using `sync :all` in just the parent. I added `sync :all` to both children models, removed from parent and now is working.
